version: '3.4'

services:
  phonecentre:
    container_name: netapi
    image: ${DOCKER_REGISTRY-}phonecentre
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network

  clientapp:
    build: 
      context: ./ClientApp
    container_name: react-client
    environment:
      - API_URL=https://host.docker.internal:44451
    ports:
      - "44450:44450"
    stdin_open: true
    tty: true
    networks:
      - network
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Qwe123!!
    networks:
      - network

  sql-server-2022:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Qwe123!!"
      ACCEPT_EULA: "Y"
    networks:
      - network

networks:
  network:
    driver: bridge