version: '3.4'

services:
  phonecentre:
    image: ${DOCKER_REGISTRY-}phonecentre
    build:
      context: .
      dockerfile: Dockerfile
  clientapp:
    build: /ClientApp
    container_name: client
    ports:
      - '443:44450'
    stdin_open: true
    tty: true
  sql-server-2022:
    container_name: SQL
    image: microsoft/mssql-server-linux:2022-latest
    ports:
      - "1344:1344"
    environment:
      SA_PASSWORD: "Qwe123!"
      ACCEPT_EULA: "Y"