version: '3.4'

services:
  phonecentre:
    container_name: Api
    image: ${DOCKER_REGISTRY-}phonecentre
    build:
      context: .
      dockerfile: Dockerfile
  clientapp:
    build: /ClientApp
    container_name: Client
    ports:
      - "44450:44450"
    stdin_open: true
    tty: true
  sql-server-2022:
    container_name: SQL
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Qwe123!!"
      ACCEPT_EULA: "Y"