version: '3.4'

services:
  phonecentre:
    container_name: Api
    image: ${DOCKER_REGISTRY-}phonecentre
    build:
      context: .
      dockerfile: Dockerfile
  clientapp:
    build: /ClientApp
    container_name: Client
    ports:
      - "44450:44450"
    stdin_open: true
    tty: true
  mongodb:
    container_name: Mongo
    image: mongo
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Qwe123!!