version: '3.4'

services:
  phonecentre:
    container_name: netapi
    image: ${DOCKER_REGISTRY-}phonecentre
    build:
      context: .
      dockerfile: Dockerfile
  clientapp:
    build: /ClientApp
    container_name: react-client
    ports:
      - "44450:44450"
    environment:
      - API_URL=https://host.docker.internal:44451
    stdin_open: true
    tty: true
    networks:
      - network
  sql-server-2022:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Qwe123!!"
      ACCEPT_EULA: "Y"

networks:
  network:
    driver: bridge